# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rR46rB94alrW-K0RUiLHXL-0LYrASPwj
"""

import math as m

dir(m)

data={"Year" : [2012,2010,2025,202024],'Sales':[200,300,400,600]}

print(data)

import pandas as pd

df = pd.DataFrame(data) # DataFrame use for Table
print(df)

Employee = {'EName':['Priyanka','Vivek','Sachin','Omkar'],'Sal':[90000,90000,70000,50000],'deptNo':[20,30,10,20],
            'Designation':['Software Eng','Manager','Account','Main AVP'],'Adress':['Pune','Baramati','Pune','Mumbai']}
Emp = pd.DataFrame(Employee)
print(Emp)

x = Emp['Sal']
print(x)
y = Emp['deptNo']
print(y)

import matplotlib.pyplot as plt

plt.plot(x,y)
plt.show()

plt.scatter(x,y)
plt.show()

def sum():
  print('Hey')

sum()

def sum(a,b):
  print(a+b)
sum(10,20)

def Odd_Even(n):
  if n % 2 == 0 :
    print("Even No")
  else :
    print("Odd No")

Odd_Even(10)

def Palindrome(num):
   n = num
   d1 = num % 10
   num = num//10
   d2 = num % 10
   num = num//10
   ans = d1*100+ d2*10 + num
   if n == ans:
     print("It is Palindome N0")
   else:
    print("It is Not Palindome No")

Palindrome(121)

num = int(input("Enter THREE digit no "))
def Palindrome(num):
   n = num
   d1 = num % 10
   num = num//10
   d2 = num % 10
   num = num//10
   ans = d1*100+ d2*10 + num
   if n == ans:
     print("It is Palindome N0")
   else:
    print("It is Not Palindome No")

Palindrome(num)

def StudentResult(rollno,name,s1,s2,s3):
  total = s1+s2+s3
  per = total/3.0
  if per >= 90:
    print("A Grade")
  elif per >= 80:
    print("B Grade")
  elif per >= 70:
    print("C Grade")
  else :
    print("Fail")

StudentResult(1,'Priyanka',90,80,70)

def printList(list):
  for i in list:
    print(i)
printList([10,20,30,40])

