# -*- coding: utf-8 -*-
"""Use_Python_Libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rR46rB94alrW-K0RUiLHXL-0LYrASPwj
"""

import math as m

dir(m)

data={"Year" : [2012,2010,2025,202024],'Sales':[200,300,400,600]}

print(data)

import pandas as pd

df = pd.DataFrame(data) # DataFrame use for Table
print(df)

Employee = {'EName':['Priyanka','Vivek','Sachin','Omkar'],'Sal':[90000,90000,70000,50000],'deptNo':[20,30,10,20],
            'Designation':['Software Eng','Manager','Account','Main AVP'],'Adress':['Pune','Baramati','Pune','Mumbai']}
Emp = pd.DataFrame(Employee)
print(Emp)

x = Emp['Sal']
print(x)
y = Emp['deptNo']
print(y)

import matplotlib.pyplot as plt

plt.plot(x,y)
plt.show()

plt.scatter(x,y)
plt.show()

def sum():
  print('Hey')

sum()

def sum(a,b):
  print(a+b)
sum(10,20)

def Odd_Even(n):
  if n % 2 == 0 :
    print("Even No")
  else :
    print("Odd No")

Odd_Even(10)

def Palindrome(num):
   n = num
   d1 = num % 10
   num = num//10
   d2 = num % 10
   num = num//10
   ans = d1*100+ d2*10 + num
   if n == ans:
     print("It is Palindome N0")
   else:
    print("It is Not Palindome No")

Palindrome(121)

num = int(input("Enter THREE digit no "))
def Palindrome(num):
   n = num
   d1 = num % 10
   num = num//10
   d2 = num % 10
   num = num//10
   ans = d1*100+ d2*10 + num
   if n == ans:
     print("It is Palindome N0")
   else:
    print("It is Not Palindome No")

Palindrome(num)

def StudentResult(rollno,name,s1,s2,s3):
  total = s1+s2+s3
  per = total/3.0
  if per >= 90:
    print("A Grade")
  elif per >= 80:
    print("B Grade")
  elif per >= 70:
    print("C Grade")
  else :
    print("Fail")

StudentResult(1,'Priyanka',90,80,70)

def printList(list):
  for i in list:
    print(i)
printList([10,20,30,40])

def sum(*args):
  print(args)
sum(10,20,30,40)

def sum(**KeyValueArgs):
  print(KeyValueArgs)
sum(a=10,b=20)

sum(name='priyanka',age=22)

def PrintData(**KeyValueArgs):
  for k,v in KeyValueArgs.items():
    print(k,v)
PrintData(a=10,b=20,name='priyanka',age=22)

#oops

class Demo:
  def add(self,a,b):  # self means reference point
    print(a+b)

d = Demo()  # object
d.add(20,20)

class Calculator:
  def add(self,a,b):
    print(a+b)
  def sub(self,a,b):
    print(a-b)
  def mul(self,a,b):
    print(a*b)
  def div(self,a,b):
    print(a/b)

c = Calculator()
c.add(10,20)
c.sub(20,10)
c.mul(10,10)
c.div(10,10)

#function using return keyword only return 1 value
def add(a,b):
  return (a+b)

x = add(10,20)
print(x)

class Calculator:
  def add(self,a,b):
    return(a+b)
  def sub(self,a,b):
    return(a-b)
  def mul(self,a,b):
    return(a*b)
  def div(self,a,b):
    return(a/b)

c = Calculator()
a = c.add(10,20)
print(a)
s = c.sub(20,10)
print(s)
m = c.mul(10,10)
print(m)
d = c.div(10,10)
print(d)

